### ISSUE TITLE
laravel 9,  laravel/ui ^4.0 support

### ISSUE THREAD

**Issue by josiahke** [skys215/laravel-ui-tabler#1]
![image](https://user-images.githubusercontent.com/8400694/185061026-31bd41a4-165e-4672-8ad3-8189360ab763.png)

tried to install this package, and getting the above error

**Comment by skys215** [comment]
Let me check if it is compatiable with `laravel/ui:^4.0`

**Comment by skys215** [comment]
One thing to mention: this package doesn't use vite to build project, uses laravel-mix instead.

**Comment by skys215** [comment]
Done. 52265f1d69ad9daa6abab83b6a910e905273b1cb

**Comment by josiahke** [comment]
thanks, was able to install

![image](https://user-images.githubusercontent.com/8400694/185308976-133e0fc9-4286-4069-8cc4-3d769aec1a3a.png)

**Comment by josiahke** [comment]
![image](https://user-images.githubusercontent.com/8400694/185313893-25c688e5-e2f6-4136-9b21-cd34db40a91e.png)
updated the package.json file as above
![image](https://user-images.githubusercontent.com/8400694/185314291-1094a46d-7a46-4182-bc5c-cf4129259367.png)
the package has been applied
